"""Initial migration

Revision ID: 333e05937511
Revises: 
Create Date: 2024-07-16 14:17:51.961506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '333e05937511'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('ingredient',
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ingredient_id')
    )
    op.create_table('recipe',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('preparation_time', sa.Integer(), nullable=False),
    sa.Column('instructions', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('recipe_id')
    )
    op.create_table('recipe_category',
    sa.Column('recipecategory_id', sa.Integer(), nullable=False),
    sa.Column('recipe', sa.Integer(), nullable=True),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['category.category_id'], ),
    sa.ForeignKeyConstraint(['recipe'], ['recipe.recipe_id'], ),
    sa.PrimaryKeyConstraint('recipecategory_id')
    )
    op.create_table('recipe_ingredient',
    sa.Column('recipeingredient_id', sa.Integer(), nullable=False),
    sa.Column('recipe', sa.Integer(), nullable=True),
    sa.Column('ingredient', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient'], ['ingredient.ingredient_id'], ),
    sa.ForeignKeyConstraint(['recipe'], ['recipe.recipe_id'], ),
    sa.PrimaryKeyConstraint('recipeingredient_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_ingredient')
    op.drop_table('recipe_category')
    op.drop_table('recipe')
    op.drop_table('ingredient')
    op.drop_table('category')
    # ### end Alembic commands ###
